name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install gradle if wrapper missing
        run: |
          if [ ! -f ./gradlew ]; then
            sudo apt-get update
            sudo apt-get install -y gradle
          fi

      - name: Make gradlew executable
        run: chmod +x ./gradlew || true

      - name: Build APK
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload APK
        - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
